spring.application.name=Book Recommendation Engine

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/book_recommendation
spring.datasource.username=postgres
spring.datasource.password=Glitch69P$

# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect