spring.application.name=Book Recommendation Engine

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/book_recommendation
spring.datasource.username=postgres
spring.datasource.password=Glitch69P$

# Optional: Hibernate/JPA configuration (recommended for ORM)
#spring.jpa.hibernate.ddl-auto=update # change this based on your needs (e.g., 'none', 'create', 'create-drop', 'update')
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect